require("items.widgets.battery")
require("items.widgets.language")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.cpu")
require("items.widgets.memory")
require("items.widgets.gitlab")
